add terraform

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,6 +40,7 @@ jobs:
         run: |
           echo "${{ steps.generate_ssh_key.outputs.ssh_private_key }}"
 
+###############################
   Deploy-PubSub:
     name: Terraform Apply PubSub
     runs-on: ubuntu-latest
@@ -55,7 +56,26 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: 1.6.6
 
+      - name: Verify GCP secret is available
+        run: |
+          if [ -z "${{ secrets.GCP_CREDENTIALS }}" ]; then
+            echo "Secret missing!"
+            exit 1
+          else
+            echo "Secret available"
+          fi
+
+      - name: Authenticate to Google Cloud
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
+          export_environment_variables: true
+###############################
   Create-Kafka-VM:
     name: Terraform Apply Kafka VM
     runs-on: ubuntu-latest
